feat(test): support travis
sw360/sw360chores pull request #31
Opened 2017-07-07 19:45 UTC by maximilianhuber

This contains a simple configuration to use travis to build sw360-dependencies and the corresponding containers.

It tests whether at the end the nginx reponds

2017-07-08 09:57 UTC, lepokle requested changes
Please check comments. At least the tomcat check must be better.

2017-07-08 09:57 UTC, lepokle commented on .travis.yml
> +  - curl -L -S -k https://localhost:8443 | grep -iq "html"
This test is not sufficient. e.g. the bad gateway page from ngnix also includes "html".

2017-07-08 09:57 UTC, lepokle commented on .travis.yml
> +# dist: precise
superfluous line?

2017-07-08 09:57 UTC, lepokle commented on .travis.yml
> +  - curl -L -S -k https://localhost:8443 | grep -iq "html"
Maybe one check for each container would be great? E.g. couch db can also be tested very easily.

2017-07-09 09:07 UTC, maximilianhuber commented
The tests currently fail randomly. The following two tests were executed on the same configuration with the same code:
- https://travis-ci.org/sw360/sw360chores/jobs/251542658
  - FAILED at 
    ```
    curl -S -k https://localhost:8443 | grep -iq "<title>Welcome - SW360</title>"
    ```
- https://travis-ci.org/sw360/sw360chores/jobs/251542652
  - SUCCESS

## 

![2017-07-09_11 03 43](https://user-images.githubusercontent.com/1187050/27992500-613c8c60-6496-11e7-9a7b-02f9fe68eef6.png)

2017-07-10 07:32 UTC, maximilianhuber commented on deployment/docker-compose.sh
> +cmdDocker="$(addSudoIfNeeded) env $(grep -v '^#' "$DIR/proxy.env" | xargs) docker"
This change allows the `docker-compose.sh` script to be called from arbitrary folders and not only as `./docker-compose.sh`

2017-07-10 07:32 UTC, maximilianhuber commented on packaging/Rakefile
> +    sh "wget -q -c -N -P #{CACHE_DIR} #{url}"
Without the quiet flag, wget produces to many lines of output which surpass the travis limit.

2017-07-10 15:10 UTC, maximilianhuber commented
**observation:** the tests which fail are chosen randomly (at least it seems so), but if a test has failed, it always fails and restarting does not help.

2017-07-12 07:30 UTC, alexbrdn reviewed
As far as I can tell, the code looks good. If only it would work reliably...

2018-02-21 13:35 UTC, maxhbr commented
superfluous due to #48

2018-02-21 13:35 UTC, closed without merging