Refactor to current docker-compose version and to support docker swarm
sw360/sw360chores pull request #56
Opened 2019-01-16 13:13 UTC by maxhbr

This implies a new and breaking way of configuring the deployment.

2019-01-30 12:50 UTC, lepokle requested changes
When running
```
./sw360chores.pl --build --watchtower --swarm -- up
```
the following warning is printed:
```
WARNING: Some services (sw360) use the 'configs' key, which will be ignored. Compose does not support 'configs' configuration - use `docker stack deploy` to deploy to a swarm.
```
How is the usage with docker swarm and sw360chores.pl?

2019-01-30 12:50 UTC, lepokle commented on deployment/docker-compose.watchtower.yml
> +# This is the main docker-compose file for the sw360 environment. It configures
This is only the compose file for the watchtower image

2019-01-30 20:49 UTC, maxhbr commented
@lepokle all your issues should have been addressed and the commits are squashed

2019-01-31 15:28 UTC, lepokle approved these changes

2019-01-31 15:28 UTC, merged