Improve proxy support
sw360/sw360chores pull request #80
Opened 2020-08-21 09:00 UTC by oheger-bosch

This PR addresses #79. It implements the following changes:

* The proxy.env configuration file is now provided as a template. The user can copy the template and modify it. The file `proxy.env` has been added to .gitignore; so it does not appear as outgoing change.
* The sw360chores.pl script now supports a new command line switch --net-host. If specified, when building docker images the network mode 'host' is enabled. This allows the containers to access the internet (e.g. when installing additional packages) when behind a proxy.

2020-08-21 13:28 UTC, maxhbr requested changes
proxy settings should not be the default

2020-08-21 13:28 UTC, maxhbr commented on configuration/proxy.env.template
> +http_proxy=http://$proxy_host:$proxy_port
Removing the comments from these lines makes the proxy settings the default. That should not be and they should only be used if proxy settings are explicitly required.

2020-08-24 04:51 UTC, oheger-bosch commented on configuration/proxy.env.template
> +http_proxy=http://$proxy_host:$proxy_port
Changed as requested; the proxy settings are now commented out.

2020-09-14 13:18 UTC, maxhbr commented
Sorry, I am not able to review it. I do not live behind a proxy with which I could test it.

2020-09-15 05:00 UTC, oheger-bosch commented
@maxhbr, I understand. But could you at least confirm that these changes do not break anything for non-proxy users?

2020-09-21 06:44 UTC, neubs-bsi commented
I just tried out this setting once with the new feature and once without. 
Without the new feature everything worked fine. 

With the new feature, I get the following error:
```
DEBUG: call: docker-compose -p sw360 -f deployment/docker-compose.yml -f deployment/docker-compose.compose.yml -f deployment/docker-compose.dev.yml up --net-host
Builds, (re)creates, starts, and attaches to containers for a service.

Unless they are already running, this command also starts any linked services.

The `docker-compose up` command aggregates the output of each container. When
the command exits, all containers are stopped. Running `docker-compose up -d`
starts the containers in the background and leaves them running.

If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.

If you want to force Compose to stop and recreate all containers, use the
`--force-recreate` flag.

Usage: up [options] [--scale SERVICE=NUM...] [SERVICE...]

Options:
    -d                         Detached mode: Run containers in the background,
                               print new container names. Incompatible with
                               --abort-on-container-exit and --timeout.
    --no-color                 Produce monochrome output.
    --no-deps                  Don't start linked services.
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
                               Incompatible with --no-recreate.
    --no-recreate              If containers already exist, don't recreate them.
                               Incompatible with --force-recreate.
    --no-build                 Don't build an image, even if it's missing.
    --no-start                 Don't start the services after creating them.
    --build                    Build images before starting containers.
    --abort-on-container-exit  Stops all containers if any container was stopped.
                               Incompatible with -d.
    -t, --timeout TIMEOUT      Use this timeout in seconds for container shutdown
                               when attached or when containers are already.
                               Incompatible with -d.
                               running. (default: 10)
    --remove-orphans           Remove containers for services not
                               defined in the Compose file
    --exit-code-from SERVICE   Return the exit code of the selected service container.
                               Implies --abort-on-container-exit.
    --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the `scale`
                               setting in the Compose file if present.
failed... at ./sw360chores.pl line 281.

```

Is there any special setup I need to consider? (I turned my vpn off, so was behind a proxy)

2020-09-21 06:59 UTC, maxhbr commented
I think you would need `./sw360chores.pl --build --net-host -- up`

2020-09-21 07:03 UTC, maxhbr requested changes
This PR moved `proxy.env` to `proxy.env.template`, so that all scripts depending on it will fail since the env file is not present. This breaks the "just download and run" workflow. And there is also no automatic mechanism which would substitute the template (compared to the other template files).

2020-09-22 09:31 UTC, neubs-bsi commented
Ah, thanks for the hint @maxhbr now both setups work for me.

2020-09-22 09:54 UTC, maxhbr commented
does the non-proxy variant also work with a fresh clone (without already pulled liferay) and without the manual creation of a proxy.env file?

2020-09-22 11:21 UTC, oheger-bosch commented
I will have to go through these places again, but as far as I see, the most scripts are implemented in a fault-tolerant way and check for the presence of the proxy.env file before they try to read it.

2020-09-23 13:56 UTC, oheger-bosch commented
New idea: I modified the perl script to create the proxy.env file as a copy from the template if it does not exist yet. So it is guaranteed that the file always exists.

2020-09-28 12:06 UTC, mcjaeger commented
(from discussion): merge this and clean up comprehensively with
* Java 11
* travis.org -> com

Currently, travis check fails at downloading tomcat8-jre8-alpin ...

2020-09-28 12:06 UTC, merged